In [1]:
import numpy
import pandas as pd

In [7]:
a = numpy.array([1,2,3,2,3,4,3,4,5,6])
b = numpy.array([7,2,10,2,7,4,9,4,9,8])

print(a, b)

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]

In [9]:
c = numpy.intersect1d(a, b)
print(c)

[2 4]

In [ ]:
#Remove the duplicates

In [11]:
dframe = pd.DataFrame({'col1':['A']*3 + ['B']*4 + ['C','B','A'],
                      'col2':[2,3,4,2,4,2,1,3,4,4]})

dframe

  col1  col2
0    A     2
1    A     3
2    A     4
3    B     2
4    B     4
5    B     2
6    B     1
7    C     3
8    B     4
9    A     4

In [12]:
df = dframe.drop_duplicates()
df

  col1  col2
0    A     2
1    A     3
2    A     4
3    B     2
4    B     4
6    B     1
7    C     3

In [17]:
df1 = dframe.drop_duplicates(subset = ['col1'])
df1.reset_index(drop = True, inplace=True, )
print(df1.to_string(index=False))

col1  col2
   A     2
   B     2
   C     3

In [16]:
df1.set_index('col1', inplace=True, )
df1

      col2
col1
A        2
B        2
C        3